name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '12.x'
        
    - name: Install Dependencies
      run: npm install  
    - name: Build
      run: npm run build 
    - name: Run tests and coverage
      run: npm run cover 
    - name: NPM publish dryrun
      run: npm publish --access public --dry-run     
    - name: Generate documentation    
      run: npm run documentation
    - name: Upload docs to hobigo.de/nextcloud-node-client
      uses: sebastianpopp/ftp-action@releases/v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "docs"
        remoteDir: "/"
    - name: Upload to codecov 1
      run: ./node_modules/.bin/codecov -t ${{ secrets.CODECOV_TOKEN }}      
    - name: Upload to codecov 2
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.lcov #optional
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
