name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'      
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install Dependencies
      run: npm install  
    - name: Build
      run: npm run build 
    - name: Run tests and coverage
      run: npm run cover 
    - name: NPM publish dryrun
      run: npm publish --access public --dry-run     
    # - name: Upload to codecov 1
      # run: ./node_modules/.bin/codecov -t ${{ secrets.CODECOV_TOKEN }}      
    - name: Upload to Codecov 
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./docs/coverage/lcov.info
        
    - name: Determine. if the version have been updated
      uses: EndBug/version-check@v1.1.1
      id: versionChange
        
    - name: Check if version has been changed
      if: steps.versionChange.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.versionChange.outputs.type }}"'
      
    - name: Publish package to NPM
      if: steps.versionChange.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
  ### documentation
#    - name: Generate documentation with typedoc
#      run: npm run documentation
#    - name: Upload API documentation to hobigo.de/nextcloud-node-client/api
#      uses: sebastianpopp/ftp-action@releases/v1
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#        user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "typedoc"
#        remoteDir: "/api"
#    - name: Upload code coverage to hobigo.de/nextcloud-node-client/coverage
#      uses: sebastianpopp/ftp-action@releases/v1
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#       user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "coverage"
#        remoteDir: "/coverage"

