name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '12.x'
        
    - name: Install Dependencies
      run: npm install  
    - name: Build
      run: npm run build 
    - name: Run tests and coverage
      run: npm run cover 
    - name: NPM publish dryrun
      run: npm publish --access public --dry-run     
    # - name: Upload to codecov 1
      # run: ./node_modules/.bin/codecov -t ${{ secrets.CODECOV_TOKEN }}      
    - name: Upload to Codecov 
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
  ### documentation
#    - name: Generate documentation with typedoc
#      run: npm run documentation
#    - name: Upload API documentation to hobigo.de/nextcloud-node-client/api
#      uses: sebastianpopp/ftp-action@releases/v1
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#        user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "typedoc"
#        remoteDir: "/api"
#    - name: Upload code coverage to hobigo.de/nextcloud-node-client/coverage
#      uses: sebastianpopp/ftp-action@releases/v1
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#       user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "coverage"
#        remoteDir: "/coverage"

#    - name: Publish if version has been updated
#      uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
#      with: # All of theses inputs are optional
#        tag_name: "v%s"
#        tag_message: "v%s"
#        commit_pattern: "^Release (\\S+)"
#      env: # More info about the environment variables in the README
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
#        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
     
